openapi: "3.0.0"
info:
  title: Ecommerce-Microservice

  version: "1.0.0"
  description: Order Service
servers:
  - url: http://localhost:8080/
paths:
  /order:
    post:
      tags:
        - Order
      summary: User places an order
      description: Add order entry
      requestBody:
        description: Request to add order of user
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderSchema"
        required: true
      responses:
        "201":
          description: Cart created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderSchema"
        "401":
          description: All data is not provided
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Amount is required
        "409":
          description: Product doesn't exist
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Product doesn't exist
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

components:
  schemas:
    OrderSchema:
      type: object
      properties:
        productId:
          type: string
        userId:
          type: string
        stock:
          type: string
        price:
          type: number
        address:
          type: object
          properties:
            street:
              type: string
            city:
              type: string
            pincode:
              type: string
            country:
              type: string
